const countryAbbreviations = {
  "usa": "united_states_of_america",
  "us": "united_states_of_america",
  "united_states": "united_states_of_america",
  "uk": "united_kingdom",
  "uae": "united_arab_emirates",
  "drc": "democratic_republic_of_the_congo",
  "congo": "republic_of_the_congo",
  "prc": "china",
  "nz": "new_zealand"

};

const allCountries = [
  "costa_rica",
  "nicaragua",
  "saint_martin",
  "sint_maarten",
  "haiti",
  "dominican_republic",
  "el_salvador",
  "guatemala",
  "cuba",
  "honduras",
  "united_states_of_america",
  "canada",
  "mexico",
  "belize",
  "panama",
  "greenland",
  "curaçao",
  "aruba",
  "the_bahamas",
  "turks_and_caicos_islands",
  "saint_pierre_and_miquelon",
  "trinidad_and_tobago",
  "grenada",
  "saint_vincent_and_the_grenadines",
  "barbados",
  "saint_lucia",
  "dominica",
  "montserrat",
  "antigua_and_barbuda",
  "saint_kitts_and_nevis",
  "united_states_virgin_islands",
  "saint_barthélemy",
  "puerto_rico",
  "anguilla",
  "british_virgin_islands",
  "jamaica",
  "cayman_islands",
  "bermuda",
  "indonesia",
  "malaysia",
  "cyprus",
  "india",
  "china",//people's_republic_of_
  "israel",
  "palestine",
  "lebanon",
  "syria",
  "south_korea",
  "north_korea",
  "bhutan",
  "oman",
  "uzbekistan",
  "kazakhstan",
  "tajikistan",
  "mongolia",
  "vietnam",
  "cambodia",
  "united_arab_emirates",
  "georgia",
  "azerbaijan",
  "turkey",
  "laos",
  "kyrgyzstan",
  "armenia",
  "iraq",
  "iran",
  "qatar",
  "saudi_arabia",
  "pakistan",
  "thailand",
  "kuwait",
  "east_timor",
  "brunei",
  "myanmar",
  "bangladesh",
  "afghanistan",
  "turkmenistan",
  "jordan",
  "nepal",
  "yemen",
  "hong_kong",
  "turkish_republic_of_northern_cyprus",
  "siachen_glacier",
  "philippines",
  "sri_lanka",
  "taiwan",
  "japan",
  "australian_indian_ocean_territories",
  "singapore",
  "bahrain",
  "macau",
  "chile",
  "bolivia",
  "peru",
  "argentina",
  "suriname",
  "guyana",
  "brazil",
  "uruguay",
  "ecuador",
  "colombia",
  "paraguay",
  "venezuela",
  "falkland_islands",
  "ethiopia",
  "south_sudan",
  "somalia",
  "kenya",
  "malawi",
  "tanzania",
  "somaliland",
  "morocco",
  "western_sahara",
  "republic_of_the_congo",
  "democratic_republic_of_the_congo",
  "namibia",
  "south_africa",
  "libya",
  "tunisia",
  "zambia",
  "sierra_leone",
  "guinea",
  "liberia",
  "central_african_republic",
  "sudan",
  "djibouti",
  "eritrea",
  "ivory_coast",
  "mali",
  "senegal",
  "nigeria",
  "benin",
  "angola",
  "botswana",
  "zimbabwe",
  "chad",
  "algeria",
  "mozambique",
  "eswatini",
  "burundi",
  "rwanda",
  "uganda",
  "lesotho",
  "cameroon",
  "gabon",
  "niger",
  "burkina_faso",
  "togo",
  "ghana",
  "guinea-bissau",
  "egypt",
  "mauritania",
  "equatorial_guinea",
  "the_gambia",
  "madagascar",
  "comoros",
  "são_tomé_and_príncipe",
  "cape_verde",
  "france",
  "ukraine",
  "belarus",
  "lithuania",
  "russia",
  "czech_republic",
  "germany",
  "estonia",
  "latvia",
  "norway",
  "sweden",
  "finland",
  "luxembourg",
  "belgium",
  "north_macedonia",
  "albania",
  "kosovo",
  "spain",
  "denmark",
  "romania",
  "hungary",
  "slovakia",
  "poland",
  "ireland",
  "united_kingdom",
  "greece",
  "austria",
  "italy",
  "switzerland",
  "netherlands",
  "liechtenstein",
  "serbia",
  "croatia",
  "slovenia",
  "bulgaria",
  "san_marino",
  "monaco",
  "andorra",
  "montenegro",
  "bosnia_and_herzegovina",
  "portugal",
  "moldova",
  "vatican_city",
  "iceland",
  "malta",
  "jersey",
  "guernsey",
  "isle_of_man",
  "åland",
  "faroe_islands",
  "papua_new_guinea",
  "australia",
  "fiji",
  "new_zealand",
  "new_caledonia",
  "pitcairn_islands",
  "french_polynesia",
  "kiribati",
  "marshall_islands",
  "norfolk_island",
  "cook_islands",
  "tonga",
  "wallis_and_futuna",
  "samoa",
  "solomon_islands",
  "tuvalu",
  "nauru",
  "federated_states_of_micronesia",
  "vanuatu",
  "niue",
  "american_samoa",
  "palau",
  "guam",
  "northern_mariana_islands",
  "ashmore_and_cartier_islands",
  "antarctica",
  "french_southern_and_antarctic_lands",
  "seychelles",
  "heard_island_and_mcdonald_islands",
  "saint_helena",
  "mauritius",
  "british_indian_ocean_territory",
  "maldives",
  "south_georgia_and_the_south_sandwich_islands"
];

function formatCountryName(name) {
  //console.log(name);
  name = String(name).toLowerCase();
  name = name.replaceAll(" ", "_");
  return name;
}

/*function isValidCountry(country) {
  const formattedCountry = formatCountryName(country);
  return allCountries.includes(formattedCountry);
}*/

function isValidCountry(input) {
  const normalizedInput = input.trim().toLowerCase().replace(/\s+/g, '_');
  if (allCountries.includes(normalizedInput)) {
      return input;
  }
  for (const [abbr, fullName] of Object.entries(countryAbbreviations)) {
      if (normalizedInput === abbr.toLowerCase() || normalizedInput === fullName.toLowerCase()) {
          return fullName;
      }
  }
  return false;
}

export { formatCountryName, isValidCountry };
